# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Barrio31' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Barrio31
pod 'Alamofire'

end
