# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Barrio31' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Barrio31
pod 'Alamofire'
pod 'SVProgressHUD'
pod 'SideMenuSwift', '0.4.0'
pod 'AlamofireImage'
pod 'Realm', '3.11.0'
pod 'RealmSwift', '3.11.0'
pod 'Kingfisher'
pod 'Gemini'
pod 'Floaty'


end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
end
